Revamped Plugin Reporter due to Librato limitations
mix/kafka-librato-monitor pull request #13
Opened 2017-05-19 04:04 UTC by ankitcha

Since librato supports graphs (& alerts) on composite metrics with a maximum limit of 256 metrics - we cannot support recording metrics as partition level - hence changed the design of plugin reporter to record (in cache) & report metrics at group-topic level by aggregating values from all partitions per topic per consumer group.

Also, the earlier version had a bug where gauges were not getting updated value from cache - fixed that as part of new design.

2017-05-19 21:15 UTC, dkjhanitt requested changes

2017-05-19 21:15 UTC, dkjhanitt commented on src/main/scala/mix/kafka/monitor/LibratoOffsetReporter.scala
> +    val mergedMetrics = mergeMetrics(existingMetrics, metricsWithUpdatedValues)
In general please include `types`. It helps in reviewing faster. Right now I have to scroll up & down to know the exact type.

2017-05-19 21:15 UTC, dkjhanitt commented on src/main/scala/mix/kafka/monitor/MetricsCacheProvider.scala
> +    import scala.collection.JavaConverters._
Since ` import scala.collection.JavaConverters._` is used in multiple methods, can we move it up ?

2017-05-19 21:23 UTC, ankitcha commented on src/main/scala/mix/kafka/monitor/LibratoOffsetReporter.scala
> +    val mergedMetrics = mergeMetrics(existingMetrics, metricsWithUpdatedValues)
let me say what I can do. The problem here is - dealing with Map of Map of java types. Including it everywhere makes it even more non-readable. I had it initially and removed it later but tried out following things to solve this concern.

I have created intermediate methods with clear names and explicit return types to try to make it manageable. Other minor thing I intentionally did was to keep the types same. So for instance, in the above method call - `mergeMetrics` both inputs and the return type have same types. Maybe I could include explicit type for the first one to make it better.

2017-05-19 21:26 UTC, dkjhanitt commented on src/main/scala/mix/kafka/monitor/LibratoOffsetReporter.scala
> +    val mergedMetrics = mergeMetrics(existingMetrics, metricsWithUpdatedValues)
Maybe `package object` may help here ?

2017-05-19 21:29 UTC, ankitcha commented on src/main/scala/mix/kafka/monitor/LibratoOffsetReporter.scala
> +    val mergedMetrics = mergeMetrics(existingMetrics, metricsWithUpdatedValues)
`package object` - ???

2017-05-19 22:20 UTC, avenka11 commented on src/main/scala/mix/kafka/monitor/MetricsCacheProvider.scala
> +case class GroupTopic(group: String, topic: String)
Since `GroupTopic` is used across classes, either move it to a separate file or add it to a package object.

2017-05-19 23:17 UTC, ashok12 submitted a review, later dismissed

2017-05-20 02:19 UTC, ankitcha commented on src/main/scala/mix/kafka/monitor/LibratoOffsetReporter.scala
> +    val mergedMetrics = mergeMetrics(existingMetrics, metricsWithUpdatedValues)
instead of using package object - I have type aliases internal within this class

2017-05-20 02:20 UTC, dkjhanitt submitted a review, later dismissed

2017-05-22 16:50 UTC, dkjhanitt approved these changes

2017-05-22 17:27 UTC, avenka11 commented on src/main/scala/mix/kafka/monitor/models.scala
> +package mix.kafka.monitor
👍

2017-05-22 17:34 UTC, ashok12 approved these changes

2017-05-22 17:35 UTC, merged